 ---
title: "Case Study 2, Pt. 2"
author: "Nathaniel Brown, In Hee Ho, Sarah Zimmermann"
date: "October 18, 2017"
output:
  pdf_document: default
  html_document: default
---
```{r, warning=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
library(ggplot2)
library(survival)
library(gridExtra)
library(dplyr)
<<<<<<< HEAD
library(survminer)

=======
library(reshape2)
>>>>>>> 7b739055c541e38e81ee38b93cc7067fcb375709
dat <- read.table("kellydat.txt", header=T)

```

```{r, fig}
dat$race = "Other"
dat$race[dat$black==1|dat$hisp==1 ]="Black or Hispanic"
dat$gender = "male"
dat$gender[dat$male==0]="female"
dat$symptom = "0"
dat$symptom[dat$sn1==1]="1"
dat$symptom[dat$sn2==1]="2"
dat$symptom[dat$sn3==1|dat$all4==1]="3+"
dat$scan="not scanned"
dat$scan[dat$fail==1]="scanned"
dat = dat %>% group_by(race) %>% mutate(racescan = ifelse(fail == 1, mean(fail), 1-mean(fail)))
dat = dat %>% group_by(symptom) %>% mutate(symptomscan = ifelse(fail == 1, mean(fail), 1-mean(fail)))
dat = dat %>% group_by(gender) %>% mutate(genderscan = ifelse(fail == 1, mean(fail), 1-mean(fail))) %>% as.data.frame()
```

###Kaplan-Meier Analysis for Race, Gender, and Clinical Presentation 

```{r}
dat.KM <- survfit(Surv(nctdel, fail) ~ 1, data = dat) #estimated survival curve 

plot(dat.KM, main=expression(paste("Kaplan-Meier Estimate ", hat(S)(t), " with CI")),
     xlab="t", ylab="Survival", lwd=2)
```

```{r}

par(mfrow=c(1,3))
dat.KM.race <- survfit(Surv(nctdel, fail) ~ race, type="kaplan-meier", conf.type="log", data=dat)

plot(dat.KM.race, main=expression(paste("KM-Est ", hat(S)[g](t), " for Race")),
     xlab="t", ylab="Survival", lwd=2, col=1:3, cex.main=0.9)
legend(x="topright", col=1:2, lwd=2, legend=c("Black/Hisp", "Other"))


dat.KM.gender <- survfit(Surv(nctdel, fail) ~ male, type="kaplan-meier", conf.type="log", data=dat)

plot(dat.KM.gender, main=expression(paste("KM-Est ", hat(S)[g](t), " for Gender")),
     xlab="t", ylab="Survival", lwd=2, col=1:2, cex.main=0.9)
legend(x="topright", col=1:2, lwd=2, legend=c("male", "female"))


dat.KM.symptom <- survfit(Surv(nctdel, fail) ~ symptom, type="kaplan-meier", conf.type="log", data=dat)

plot(dat.KM.symptom, main=expression(paste("KM-Est ", hat(S)[g](t), " for Clinical Presentation")),
     xlab="t", ylab="Survival", lwd=2, col=1:4, cex.main=0.9)
legend(x="topright", col=1:4, lwd=2, legend=c("0", "1", "2", "3+"))


```


### Logistic Regression
```{r logit}

lower_bound <- function(x, bounds){
  ret <- rep(NA, length(x))
  for(i in 1:length(x)){
    xi <- x[i]
    found <- (which(xi >= c(-Inf, bounds) & (xi <= c(bounds, Inf))))[1] - 1
    if(found==0){found<-1}
    ret[i] <- bounds[found]
  }
  return(ret)
}

bounds <- seq(0, floor(max(dat$nctdel)))

dat$timecat <- lower_bound(dat$nctdel, bounds)
dat$personid <- 1:nrow(dat)
datcat <- merge(dat$personid, bounds) %>% 
          unique() %>% 
          rename(personid=x, timecat=y) %>% 
          arrange(personid, timecat) %>% 
            #take all unique combinations of people and time categories
          merge(dat, by=c("personid", "timecat"), all=TRUE) %>%
          #select(personid, timecat, fail) %>%
          mutate(fail = ifelse(is.na(fail), 0, fail)) %>%
            #add fail column
          group_by(personid) %>%
          mutate(maxtimecat = max(timecat[fail==1]),
                 atrisk = (fail==1 | timecat < maxtimecat)) %>%
            #for each person, identify rows where persons are not at risk (after they fail), and remove those rows
          filter(atrisk) %>%
          select(personid, timecat, fail) %>%
          as.data.frame()


dcast(test, personid ~ timecat, fun.aggregate = seq, from=1, to=timecat)
```


```{r}
 
fitCPH_gender<- coxph(Surv(nctdel, fail) ~ gender, data=dat)
summary(fitCPH_gender)


#diagnostics
extractAIC(fitCPH_gender)

ggcoxdiagnostics(fitCPH_gender, type = "dfbeta",
                 linear.predictions = FALSE, ggtheme = theme_bw())#influential points
ggcoxdiagnostics(fitCPH_gender, type = "deviance",
                 linear.predictions = FALSE, ggtheme = theme_bw()) #residuals
#ggcoxfunctional(Surv(nctdel, fail) ~ gender, data=dat) #linearity 

```

```{r}
fitCPH_race<- coxph(Surv(nctdel, fail) ~ race, data=dat)
summary(fitCPH_race)
extractAIC(fitCPH_race)


ggcoxdiagnostics(fitCPH_race, type = "dfbeta",
                 linear.predictions = FALSE, ggtheme = theme_bw())#influential points
ggcoxdiagnostics(fitCPH_race, type = "deviance",
                 linear.predictions = FALSE, ggtheme = theme_bw()) #residuals
#ggcoxfunctional(Surv(nctdel, fail) ~ race, data=dat) #linearity 


```


```{r}

fitCPH_symptom<- coxph(Surv(nctdel, fail) ~ symptom, data=dat)
summary(fitCPH_symptom)
extractAIC(fitCPH_symptom)


ggcoxdiagnostics(fitCPH_symptom, type = "dfbeta",
                 linear.predictions = FALSE, ggtheme = theme_bw())#influential points
ggcoxdiagnostics(fitCPH_symptom, type = "deviance",
                 linear.predictions = FALSE, ggtheme = theme_bw()) #residuals
#ggcoxfunctional(Surv(nctdel, fail) ~ symptom, data=dat) #linearity 

```


#References

http://influentialpoints.com/Training/coxs_proportional_hazards_regression_model-principles-properties-assumptions.htm#modmch


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3059453/


http://dwoll.de/rexrepos/posts/survivalKM.html

http://www.sthda.com/english/wiki/cox-model-assumptions 


<!--
These are the assumptions for Cox regression according to the link: 

1.    The mechanisms giving rise to censoring of individuals must not be related to the probability of an event occurring. This assumption is known as non-informative censoring and applies for nearly all forms of survival analysis.

2.    Survival curves for different strata must have hazard functions that are proportional over time. This is the proportional hazards assumption discussed above for a single explanatory variable and for the multivariate model.

3.    There should be a linear relationship between the log hazard and each covariate. This is best checked using residual plots

-->
